import Head from 'next/head'
import DatePickerButton from '../components/DatePicker'
import TimePickerButton from '../components/TimePicker'
import SelectedDatesAndTimes from '../components/SelectedDatesAndTimes'
export default function Home() {
  return (
    <>
      <Head>
        <title>Skejoodle | Create Meeting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SelectedDatesAndTimes />
      </main>
    </>
  )
}
